## Introduction to Numpy
* NumPy is a python library.
* Can work in the domain of linear algebra, fourier transformation and matrices.
* NumPy stands for Numerical Python.
* NumPy uses the array object called `ndarray`.
* NumPy array is faster than list because it uses a memory allocation system named **contiguous memory allocation**. [More Info](https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/)
* **Contiguous Memory Allocation**: Contiguous memory allocation is basically a method in which a single contiguous section/part of memory is allocated to a process or file needing it. Because of this all the available memory space resides at the same place together, which means that the freely/unused available memory partitions are not distributed in a random fashion here and there across the whole memory space.  [More Info](https://www.geeksforgeeks.org/difference-between-contiguous-and-noncontiguous-memory-allocation/) and a [Youtube](https://youtu.be/eHzUtmPGfJw) video.

    ![Contiguous Memory](../images/coniguousMemory.jpg)
* NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in **C or C++**.
* The source code for NumPy is located at this [github repository](https://github.com/numpy/numpy).

### Some important points about Numpy arrays:

* We can create an N-dimensional array in python using `Numpy.array()`.
* The array is by default Homogeneous, which means data inside an array must be of the same Datatype. (**Note you can also create a structured array in python**).
* Element-wise operation is possible.
* Numpy array has various functions, methods, and variables, to ease our task of matrix computation.
* Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have the same number of columns. Or a three dimensioned array must have the same number of rows and columns on each card.

In [1]:
#Importing NumPy as alias np
import numpy as np
np

<module 'numpy' from 'e:\\app\\Python\\lib\\site-packages\\numpy\\__init__.py'>

In [2]:
# Version Check
print(np.__version__)

1.21.6


## All'bout Array

In [3]:
# Creating NumPy arrays
arr = np.array([1, 2, 3, 4, 5])
# Alternative way
alArr = np.arange(1,6)
print('This is Array {} and this created in an alternative way {}'.format(arr, alArr))
print(print('Both this {} and this {} same type'.format(type(arr), type(alArr))))

# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
itTuple = (1, 5, 6)
convertedArray = np.array(itTuple)
print(convertedArray)
print(type(convertedArray))


This is Array [1 2 3 4 5] and this created in an alternative way [1 2 3 4 5]
Both this <class 'numpy.ndarray'> and this <class 'numpy.ndarray'> same type
None
[1 5 6]
<class 'numpy.ndarray'>


### Dimension of Array
* A dimension in arrays is one level of array depth (nested array).
* **Nested Array**: Nested arrays that have arrays as their elements.
* 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
* An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
* An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors.
* An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.
* An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument.

In [4]:
# 0-D Array
O_D = np.array(33)
I_D = np.array([32, 65, 12, 33])
II_D = np.array([[33, 34, 35],[22, 23, 24]])
III_D = np.array([[[33, 34, 35],[22, 23, 24]],[[39, 37, 36],[22, 22, 25]]])

#Setting the dimension by 'ndmin'
N_D = np.array([[[33, 34, 35],[22, 23, 24]],[[39, 37, 36],[22, 22, 25]]], ndmin=6)

# Printing the arrays and their dimensions
print('This is 0-D array: \n {}, \n\n This is 1-D array: \n {}, \n\n This is 2-D array: \n {}, \n\n This is 3-D array: \n {}, \n\n This is N-D array: \n {}'.format(O_D, I_D, II_D, III_D, N_D))

print('Dimension of 0-D array: \n {}, \n\n Dimension of 1-D array: \n {}, \n\n Dimension of 2-D array: \n {}, \n\n Dimension of 3-D array: \n {}, \n\n Dimension of N-D array: \n {}'.format(O_D.ndim, I_D.ndim, II_D.ndim, III_D.ndim, N_D.ndim))

This is 0-D array: 
 33, 

 This is 1-D array: 
 [32 65 12 33], 

 This is 2-D array: 
 [[33 34 35]
 [22 23 24]], 

 This is 3-D array: 
 [[[33 34 35]
  [22 23 24]]

 [[39 37 36]
  [22 22 25]]], 

 This is N-D array: 
 [[[[[[33 34 35]
     [22 23 24]]

    [[39 37 36]
     [22 22 25]]]]]]
Dimension of 0-D array: 
 0, 

 Dimension of 1-D array: 
 1, 

 Dimension of 2-D array: 
 2, 

 Dimension of 3-D array: 
 3, 

 Dimension of N-D array: 
 6


In [5]:
# Accessing an array 
# I_D = np.array([32, 65, 12, 33])
# II_D = np.array([[33, 34, 35],[22, 23, 24]])
# III_D = np.array([[[33, 34, 35],[22, 23, 24]],[[39, 37, 36],[22, 22, 25]]])
print(I_D[0] + I_D[-1]) # positive indexing access an array frontwise and negative indexing access an array backwise.

# Accessing 2-D array
print(II_D[0,1]) # here first argument select the element and second aregument access that elements values.

# Accessing 3_D array 
print(III_D[0,1,2]) # first argument 2D array, second one select 1D array and third argument gets the value wanted.

# to access nD array we first need to know its dimension and we can input arguments accordingly.

65
34
24


In [7]:
# Slicing an Array
# Slicing in python means taking elements from one given index to another given index.
#arr = np.array([1, 2, 3, 4, 5])
# I_D = np.array([32, 65, 12, 33])
# II_D = np.array([[33, 34, 35],[22, 23, 24]])
# III_D = np.array([[[33, 34, 35],[22, 23, 24]],[[39, 37, 36],[22, 22, 25]]])

print(arr[1:4]) #first argument included and second element excluded.
print(arr[:4]) # from start to third element
print(arr[4:]) # From fourth to last
print(arr[-1:-4]) # It will give an empty array because this indexing will start from the last and will go on forward.
print(arr[-1:-4:-1]) # however,It will give an array as we have justified the step to go backward.[5,4,3]
print(arr[-4:-1]) # This will give [2,3,4]

print(II_D[1, 1:4]) # Accessing 2D array
print(III_D[0, 1, 1:3]) # Accessing 3D array

# Slicing with step 
print(arr[1:5:2]) # Will include every second element starting from index one.
print(arr[::2]) # Will include every second element

[2 3 4]
[1 2 3 4]
[5]
[]
[5 4 3]
[2 3 4]
[23 24]
[23 24]
[2 4]
[1 3 5]


## Data Types in NumPy
* NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

* Below is a list of all data types in NumPy and the characters used to represent them.

* `i` - integer.
* `b` - boolean.
* `u` - unsigned integer.
* `f` - float.
* `c` - complex float.
* `m` - timedelta.
* `M` - datetime.
* `O` - object.
* `S` - string.
* `U` - unicode string.
* `V` - fixed chunk of memory for other type ( void ).
* The NumPy array object has a property called `dtype` that returns the data type of the array.

In [9]:
# Getting to know the data type.
print(arr.dtype) # Result will be according to the element of that array.
ar2 = np.array([1, 2, 3, 4], dtype='S')

print(ar2)
print('Data of ar2 is:',ar2.dtype)

# Creating data types with specified data types. For i, u, f, S and U we can define size as well.
ar = np.array([34, 56, 75], dtype='i4')
ar1 = np.array([34, 56, 75])
print('this is data type of ar: {} \n\n This is the data type of ar1: {}'.format(ar.dtype, ar1.dtype))

""" In terms of visual representation and how the array behaves when accessed or manipulated, there won't be any noticeable differences between dtype='i4' and dtype='i' for the given array [1, 2, 3, 4].

The primary distinction lies in the memory allocation and the size of the integer data type used to store each element in the array.

By specifying dtype='i4', you explicitly indicate that each element should be represented as a 32-bit signed integer, allocating 4 bytes of memory for each element.

On the other hand, using dtype='i' lets NumPy choose the default integer data type based on the platform's architecture. This default data type is often either a 32-bit or 64-bit signed integer, depending on the platform. This choice affects the memory allocation for each element accordingly.

In terms of functionality and behavior, both arrays will behave similarly for basic operations. However, the memory usage and potential impact on performance may differ depending on the size of the data type chosen."""

int32
[b'1' b'2' b'3' b'4']
Data of ar2 is: |S1
this is data type of ar: int32 

 This is the data type of ar1: int32


" In terms of visual representation and how the array behaves when accessed or manipulated, there won't be any noticeable differences between dtype='i4' and dtype='i' for the given array [1, 2, 3, 4].\n\nThe primary distinction lies in the memory allocation and the size of the integer data type used to store each element in the array.\n\nBy specifying dtype='i4', you explicitly indicate that each element should be represented as a 32-bit signed integer, allocating 4 bytes of memory for each element.\n\nOn the other hand, using dtype='i' lets NumPy choose the default integer data type based on the platform's architecture. This default data type is often either a 32-bit or 64-bit signed integer, depending on the platform. This choice affects the memory allocation for each element accordingly.\n\nIn terms of functionality and behavior, both arrays will behave similarly for basic operations. However, the memory usage and potential impact on performance may differ depending on the size of t

### What if a Value Can Not Be Converted?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.

> **ValueError:** In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [10]:
# A non integer string like 'a' can not be converted to integer (will raise an error):
ar4= np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

## Converting Data Type on Existing Arrays
> The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

**The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.**

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [13]:
ar5 = np.array([1.1, 0, 2.1, 3.1])

newarr = ar5.astype('i') # newarr = arr.astype(int), int as parameter or newarr = arr.astype(bool), bool for boolean.
newar5 = ar5.astype(bool)
print(newarr)
print(newar5)
print(newarr.dtype)
print(newar5.dtype)

[1 0 2 3]
[ True False  True  True]
int32
bool
