## Introduction to Numpy
* NumPy is a python library.
* Can work in the domain of linear algebra, fourier transformation and matrices.
* NumPy stands for Numerical Python.
* NumPy uses the array object called `ndarray`.
* NumPy array is faster than list because it uses a memory allocation system named **contiguous memory allocation**. [More Info](https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/)
* **Contiguous Memory Allocation**: Contiguous memory allocation is basically a method in which a single contiguous section/part of memory is allocated to a process or file needing it. Because of this all the available memory space resides at the same place together, which means that the freely/unused available memory partitions are not distributed in a random fashion here and there across the whole memory space.  [More Info](https://www.geeksforgeeks.org/difference-between-contiguous-and-noncontiguous-memory-allocation/) and a [Youtube](https://youtu.be/eHzUtmPGfJw) video.

    ![Contiguous Memory](../images/coniguousMemory.jpg)
* NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in **C or C++**.
* The source code for NumPy is located at this [github repository](https://github.com/numpy/numpy).

### Some important points about Numpy arrays:

* We can create an N-dimensional array in python using `Numpy.array()`.
* The array is by default Homogeneous, which means data inside an array must be of the same Datatype. (**Note you can also create a structured array in python**).
* Element-wise operation is possible.
* Numpy array has various functions, methods, and variables, to ease our task of matrix computation.
* Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have the same number of columns. Or a three dimensioned array must have the same number of rows and columns on each card.

In [1]:
#Importing NumPy as alias np
import numpy as np
np

<module 'numpy' from 'e:\\app\\Python\\lib\\site-packages\\numpy\\__init__.py'>

In [2]:
# Version Check
print(np.__version__)

1.21.6


## All'bout Array

In [3]:
# Creating NumPy arrays
arr = np.array([1, 2, 3, 4, 5])
# Alternative way
alArr = np.arange(1,6)
print('This is Array {} and this created in an alternative way {}'.format(arr, alArr))
print(print('Both this {} and this {} same type'.format(type(arr), type(alArr))))

# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
itTuple = (1, 5, 6)
convertedArray = np.array(itTuple)
print(convertedArray)
print(type(convertedArray))


This is Array [1 2 3 4 5] and this created in an alternative way [1 2 3 4 5]
Both this <class 'numpy.ndarray'> and this <class 'numpy.ndarray'> same type
None
[1 5 6]
<class 'numpy.ndarray'>


### Dimension of Array
* A dimension in arrays is one level of array depth (nested array).
* **Nested Array**: Nested arrays that have arrays as their elements.
* 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
* An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
* An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors.
* An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.
* An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument.

In [4]:
# 0-D Array
O_D = np.array(33)
I_D = np.array([32, 65, 12, 33])
II_D = np.array([[33, 34, 35],[22, 23, 24]])
III_D = np.array([[[33, 34, 35],[22, 23, 24]],[[39, 37, 36],[22, 22, 25]]])

#Setting the dimension by 'ndmin'
N_D = np.array([[[33, 34, 35],[22, 23, 24]],[[39, 37, 36],[22, 22, 25]]], ndmin=6)

# Printing the arrays and their dimensions
print('This is 0-D array: \n {}, \n\n This is 1-D array: \n {}, \n\n This is 2-D array: \n {}, \n\n This is 3-D array: \n {}, \n\n This is N-D array: \n {}'.format(O_D, I_D, II_D, III_D, N_D))

print('Dimension of 0-D array: \n {}, \n\n Dimension of 1-D array: \n {}, \n\n Dimension of 2-D array: \n {}, \n\n Dimension of 3-D array: \n {}, \n\n Dimension of N-D array: \n {}'.format(O_D.ndim, I_D.ndim, II_D.ndim, III_D.ndim, N_D.ndim))

This is 0-D array: 
 33, 

 This is 1-D array: 
 [32 65 12 33], 

 This is 2-D array: 
 [[33 34 35]
 [22 23 24]], 

 This is 3-D array: 
 [[[33 34 35]
  [22 23 24]]

 [[39 37 36]
  [22 22 25]]], 

 This is N-D array: 
 [[[[[[33 34 35]
     [22 23 24]]

    [[39 37 36]
     [22 22 25]]]]]]
Dimension of 0-D array: 
 0, 

 Dimension of 1-D array: 
 1, 

 Dimension of 2-D array: 
 2, 

 Dimension of 3-D array: 
 3, 

 Dimension of N-D array: 
 6


In [5]:
# Accessing an array 
# I_D = np.array([32, 65, 12, 33])
# II_D = np.array([[33, 34, 35],[22, 23, 24]])
# III_D = np.array([[[33, 34, 35],[22, 23, 24]],[[39, 37, 36],[22, 22, 25]]])
print(I_D[0] + I_D[-1]) # positive indexing access an array frontwise and negative indexing access an array backwise.

# Accessing 2-D array
print(II_D[0,1]) # here first argument select the element and second aregument access that elements values.

# Accessing 3_D array 
print(III_D[0,1,2]) # first argument 2D array, second one select 1D array and third argument gets the value wanted.

# to access nD array we first need to know its dimension and we can input arguments accordingly.

65
34
24


In [6]:
# Slicing an Array
# Slicing in python means taking elements from one given index to another given index.
#arr = np.array([1, 2, 3, 4, 5])
# I_D = np.array([32, 65, 12, 33])
# II_D = np.array([[33, 34, 35],[22, 23, 24]])
# III_D = np.array([[[33, 34, 35],[22, 23, 24]],[[39, 37, 36],[22, 22, 25]]])

print(arr[1:4]) #first argument included and second element excluded.
print(arr[:4]) # from start to third element
print(arr[4:]) # From fourth to last
print(arr[-1:-4]) # It will give an empty array because this indexing will start from the last and will go on forward.
print(arr[-1:-4:-1]) # however,It will give an array as we have justified the step to go backward.[5,4,3]
print(arr[-4:-1]) # This will give [2,3,4]

print(II_D[1, 1:4]) # Accessing 2D array
print(III_D[0, 1, 1:3]) # Accessing 3D array

# Slicing with step 
print(arr[1:5:2]) # Will include every second element starting from index one.
print(arr[::2]) # Will include every second element

[2 3 4]
[1 2 3 4]
[5]
[]
[5 4 3]
[2 3 4]
[23 24]
[23 24]
[2 4]
[1 3 5]


## Data Types in NumPy
* NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

* Below is a list of all data types in NumPy and the characters used to represent them.

* `i` - integer.
* `b` - boolean.
* `u` - unsigned integer.
* `f` - float.
* `c` - complex float.
* `m` - timedelta.
* `M` - datetime.
* `O` - object.
* `S` - string.
* `U` - unicode string.
* `V` - fixed chunk of memory for other type ( void ).
* The NumPy array object has a property called `dtype` that returns the data type of the array.

In [7]:
# Getting to know the data type.
print(arr.dtype) # Result will be according to the element of that array.
ar2 = np.array([1, 2, 3, 4], dtype='S')

print(ar2)
print('Data of ar2 is:',ar2.dtype)

# Creating data types with specified data types. For i, u, f, S and U we can define size as well.
ar = np.array([34, 56, 75], dtype='i4')
ar1 = np.array([34, 56, 75])
print('this is data type of ar: {} \n\n This is the data type of ar1: {}'.format(ar.dtype, ar1.dtype))

""" In terms of visual representation and how the array behaves when accessed or manipulated, there won't be any noticeable differences between dtype='i4' and dtype='i' for the given array [1, 2, 3, 4].

The primary distinction lies in the memory allocation and the size of the integer data type used to store each element in the array.

By specifying dtype='i4', you explicitly indicate that each element should be represented as a 32-bit signed integer, allocating 4 bytes of memory for each element.

On the other hand, using dtype='i' lets NumPy choose the default integer data type based on the platform's architecture. This default data type is often either a 32-bit or 64-bit signed integer, depending on the platform. This choice affects the memory allocation for each element accordingly.

In terms of functionality and behavior, both arrays will behave similarly for basic operations. However, the memory usage and potential impact on performance may differ depending on the size of the data type chosen."""

int32
[b'1' b'2' b'3' b'4']
Data of ar2 is: |S1
this is data type of ar: int32 

 This is the data type of ar1: int32


" In terms of visual representation and how the array behaves when accessed or manipulated, there won't be any noticeable differences between dtype='i4' and dtype='i' for the given array [1, 2, 3, 4].\n\nThe primary distinction lies in the memory allocation and the size of the integer data type used to store each element in the array.\n\nBy specifying dtype='i4', you explicitly indicate that each element should be represented as a 32-bit signed integer, allocating 4 bytes of memory for each element.\n\nOn the other hand, using dtype='i' lets NumPy choose the default integer data type based on the platform's architecture. This default data type is often either a 32-bit or 64-bit signed integer, depending on the platform. This choice affects the memory allocation for each element accordingly.\n\nIn terms of functionality and behavior, both arrays will behave similarly for basic operations. However, the memory usage and potential impact on performance may differ depending on the size of t

### What if a Value Can Not Be Converted?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.

> **ValueError:** In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [8]:
# A non integer string like 'a' can not be converted to integer (will raise an error):
ar4= np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

## Converting Data Type on Existing Arrays
> The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

**The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.**

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
ar5 = np.array([1.1, 0, 2.1, 3.1])

newarr = ar5.astype('i') # newarr = arr.astype(int), int as parameter or newarr = arr.astype(bool), bool for boolean.
newar5 = ar5.astype(bool)
print(newarr)
print(newar5)
print(newarr.dtype)
print(newar5.dtype)

[1 0 2 3]
[ True False  True  True]
int32
bool


In [ ]:
# Numpy COPY vs VIEW
newone = np.array(['ali', 'naeem', 'sadaf', 'rabby', 'nowshad'])
x1 = newone.copy() # it is new copy of original and ows the  elements of the newone array. Changing newone array will not affect x1.
x2 = newone.view() # Changing newone array will not affect x1.
newone[-1] = 'fayed'
print('This is original',newone)
print('This is copy',x1)
print('This is view',x2)

# Check if Array Owns its Data
# As mentioned above, copies owns the data, and views does not own the data.
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.

print(x1.base) # it will return none as it owns the data.
print(x2.base) # it will refer to the original as it doesn't own the data.

This is original ['ali' 'naeem' 'sadaf' 'rabby' 'fayed']
This is copy ['ali' 'naeem' 'sadaf' 'rabby' 'nowshad']
This is view ['ali' 'naeem' 'sadaf' 'rabby' 'fayed']
None
['ali' 'naeem' 'sadaf' 'rabby' 'fayed']


In [ ]:
# Shape of You(Array)
# The shape of an array is the number of elements in each dimension.
ar7 = np.array([[1,2,3,4,5,6,7],[2,3,4,5,6,7,8]])
print(ar7.shape) # it will return (2,7) which means it has 2 dimensions where first one has 2 elements and the second one has 7 elements
# Note that every array has to have same amount of elements. otherwise it will invoke deprication error.
ar6 = np.array([1,2,3,4,6], ndmin=6)
print(ar6.shape) # it will return the shape tuple (1,1,1,1,1,5)


# By reshaping we can add or remove dimensions or change number of elements in each dimension.
ar8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
ar9 = ar8.reshape(4,3)
print(ar9) # 1D to 2D
# The product of the arguments within reshape fuction has to be equal to the total amount of array element. Otherwise it will invoke an error.
print(ar8.reshape(3,2,2)) # 1D to 3D
print(ar9.reshape(3,2,2)) # 2D to 3D
print(ar8.reshape(3,2,-1)) # 1D to 3D with an unknown dimension, NumPy will calculate it for us.

ar10 = ar9.reshape(3,2,2)
x3 = ar10.reshape(-1) # 3D to 1D, it is also called flattening an array.
print(x3.shape)

# There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

(2, 7)
(1, 1, 1, 1, 1, 5)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(12,)


In [ ]:
# Iterating through the array
# Using for loop
y1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
y2 = np.array([[[7, 8, 9], [10, 11, 12]]])
y3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in y1:
    print('Elements of y1',x)

for x in y2:
    print('Elements of y2',x)

for x in y2:
    for y in x:
        print('All elements of y2', x)    

for x in y3:
    print('Elements of y3',x)

for x in y3:
    for y in x:
        for z in y:
            print('All elements of y3',x)

# Using nditter we don't need to repeat for loop
for x in np.nditer(y3):
    print('All elements using nditer',x)

# To print the output with different data types
for x in np.nditer(y1, flags=['buffered'], op_dtypes=['S']):
  print('Converting all the elements to string',x)

# Printing with skiping steps
for x in np.nditer(y2[:, ::2]):
  print('Printing with skiping steps',x)

# Enamurating the elements
for idx, x in np.ndenumerate(y1):
  print(idx, x)
for idx, x in np.ndenumerate(y2):
  print(idx, x)
for idx, x in np.ndenumerate(y3):
  print(idx, x)

Elements of y1 1
Elements of y1 2
Elements of y1 3
Elements of y1 4
Elements of y1 5
Elements of y1 6
Elements of y1 7
Elements of y1 8
Elements of y1 9
Elements of y1 10
Elements of y1 11
Elements of y1 12
Elements of y2 [[ 7  8  9]
 [10 11 12]]
All elements of y2 [[ 7  8  9]
 [10 11 12]]
All elements of y2 [[ 7  8  9]
 [10 11 12]]
Elements of y3 [[1 2 3]
 [4 5 6]]
Elements of y3 [[ 7  8  9]
 [10 11 12]]
All elements of y3 [[1 2 3]
 [4 5 6]]
All elements of y3 [[1 2 3]
 [4 5 6]]
All elements of y3 [[1 2 3]
 [4 5 6]]
All elements of y3 [[1 2 3]
 [4 5 6]]
All elements of y3 [[1 2 3]
 [4 5 6]]
All elements of y3 [[1 2 3]
 [4 5 6]]
All elements of y3 [[ 7  8  9]
 [10 11 12]]
All elements of y3 [[ 7  8  9]
 [10 11 12]]
All elements of y3 [[ 7  8  9]
 [10 11 12]]
All elements of y3 [[ 7  8  9]
 [10 11 12]]
All elements of y3 [[ 7  8  9]
 [10 11 12]]
All elements of y3 [[ 7  8  9]
 [10 11 12]]
All elements using nditer 1
All elements using nditer 2
All elements using nditer 3
All elements us

In [ ]:
# Joining arrays
# Joining means putting contents of two or more arrays in a single array.
# In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

z1 = np.array([1,2,3])
z2 = np.array([3,4,5])
z3 = np.array([[3,4,5],[1,2,3]])
z4 = np.array([[3,4,5],[4,7,9]])

print('This array is made from concatenate',np.concatenate((z1,z2)))
print('This 2D array is made from concatenate',np.concatenate((z3,z4),axis=1))
print('This 2D array is made from stack',np.stack((z1,z2),axis=1))
print('This 2D array is made from hstack',np.hstack((z1,z2)))
print('This 2D array is made from vstack',np.vstack((z1,z2)))
print('This 2D array is made from dstack',np.dstack((z1,z2)))

This array is made from concatenate [1 2 3 3 4 5]
This 2D array is made from concatenate [[3 4 5 3 4 5]
 [1 2 3 4 7 9]]
This 2D array is made from stack [[1 3]
 [2 4]
 [3 5]]
This 2D array is made from hstack [1 2 3 3 4 5]
This 2D array is made from vstack [[1 2 3]
 [3 4 5]]
This 2D array is made from dstack [[[1 3]
  [2 4]
  [3 5]]]


In [ ]:
# Spliting arrays 
# y1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print('Spliting an array',np.array_split(y1,3))
print('Spliting an array',np.split(y1,3))
print('Spliting an array',np.split(y1,5)) # Split will not work here as for split will only work for equal size 

# We can use hsplit, vsplit and dsplit also.

Spliting an array [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
Spliting an array [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


ValueError: array split does not result in an equal division

In [10]:
# Searching array
# Using where
z5 = np.array([1,2,3,4,5,4,5,3,6,7,8,2,5,4])
print('Where element = 4:',np.where(z5 == 4))
print('Where elements are even:',np.where(z5%2 == 0))
print('Where elements are odd:',np.where(z5%2 == 1))

# Using searchsorted
print('Where element = 7:', np.searchsorted(arr, 7))
print('Where element = 7:', np.searchsorted(arr, 7, side = 'right'))
print('Where elements should be inserted:', np.searchsorted(arr, [6,7,8]))

Where element = 4: (array([ 3,  5, 13], dtype=int64),)
Where elements are even: (array([ 1,  3,  5,  8, 10, 11, 13], dtype=int64),)
Where elements are odd: (array([ 0,  2,  4,  6,  7,  9, 12], dtype=int64),)
Where element = 7: 5
Where element = 7: 5
Where elements should be inserted: [5 5 5]
