## Introduction to Numpy
* NumPy is a python library.
* Can work in the domain of linear algebra, fourier transformation and matrices.
* NumPy stands for Numerical Python.
* NumPy uses the array object called `ndarray`.
* NumPy array is faster than list because it uses a memory allocation system named **contiguous memory allocation**. [More Info](https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/)
* **Contiguous Memory Allocation**: Contiguous memory allocation is basically a method in which a single contiguous section/part of memory is allocated to a process or file needing it. Because of this all the available memory space resides at the same place together, which means that the freely/unused available memory partitions are not distributed in a random fashion here and there across the whole memory space.  [More Info](https://www.geeksforgeeks.org/difference-between-contiguous-and-noncontiguous-memory-allocation/) and a [Youtube](https://youtu.be/eHzUtmPGfJw) video.

    ![Contiguous Memory](../images/coniguousMemory.jpg)
* NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in **C or C++**.
* The source code for NumPy is located at this [github repository](https://github.com/numpy/numpy).

### Some important points about Numpy arrays:

* We can create an N-dimensional array in python using `Numpy.array()`.
* The array is by default Homogeneous, which means data inside an array must be of the same Datatype. (**Note you can also create a structured array in python**).
* Element-wise operation is possible.
* Numpy array has various functions, methods, and variables, to ease our task of matrix computation.
* Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have the same number of columns. Or a three dimensioned array must have the same number of rows and columns on each card.

In [3]:
#Importing NumPy as alias np
import numpy as np
np

<module 'numpy' from 'e:\\app\\Python\\lib\\site-packages\\numpy\\__init__.py'>

In [4]:
# Version Check
print(np.__version__)

1.21.6


## All'bout Array

In [5]:
# Creating NumPy arrays
arr = np.array([1, 2, 3, 4, 5])
# Alternative way
alArr = np.arange(1,6)
print('This is Array {} and this created in an alternative way {}'.format(arr, alArr))
print(print('Both this {} and this {} same type'.format(type(arr), type(alArr))))

# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
itTuple = (1, 5, 6)
convertedArray = np.array(itTuple)
print(convertedArray)
print(type(convertedArray))


This is Array [1 2 3 4 5] and this created in an alternative way [1 2 3 4 5]
Both this <class 'numpy.ndarray'> and this <class 'numpy.ndarray'> same type
None
[1 5 6]
<class 'numpy.ndarray'>


### Dimension of Array
* A dimension in arrays is one level of array depth (nested array).
* **Nested Array**: Nested arrays that have arrays as their elements.
* 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
* An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
* An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors.
* An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.
* An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument.

In [6]:
# 0-D Array
O_D = np.array(33)
I_D = np.array([32, 65, 12, 33])
II_D = np.array([[33, 34, 35],[22, 23, 24]])
III_D = np.array([[[33, 34, 35],[22, 23, 24]],[[39, 37, 36],[22, 22, 25]]])

#Setting the dimension by 'ndmin'
N_D = np.array([[[33, 34, 35],[22, 23, 24]],[[39, 37, 36],[22, 22, 25]]], ndmin=6)

# Printing the arrays and their dimensions
print('This is 0-D array: \n {}, \n\n This is 1-D array: \n {}, \n\n This is 2-D array: \n {}, \n\n This is 3-D array: \n {}, \n\n This is N-D array: \n {}'.format(O_D, I_D, II_D, III_D, N_D))

print('Dimension of 0-D array: \n {}, \n\n Dimension of 1-D array: \n {}, \n\n Dimension of 2-D array: \n {}, \n\n Dimension of 3-D array: \n {}, \n\n Dimension of N-D array: \n {}'.format(O_D.ndim, I_D.ndim, II_D.ndim, III_D.ndim, N_D.ndim))

This is 0-D array: 
 33, 

 This is 1-D array: 
 [32 65 12 33], 

 This is 2-D array: 
 [[33 34 35]
 [22 23 24]], 

 This is 3-D array: 
 [[[33 34 35]
  [22 23 24]]

 [[39 37 36]
  [22 22 25]]], 

 This is N-D array: 
 [[[[[[33 34 35]
     [22 23 24]]

    [[39 37 36]
     [22 22 25]]]]]]
Dimension of 0-D array: 
 0, 

 Dimension of 1-D array: 
 1, 

 Dimension of 2-D array: 
 2, 

 Dimension of 3-D array: 
 3, 

 Dimension of N-D array: 
 6
