## Basics of Linear Algebra

In [1]:
import numpy as np

### Vector Operation

![Operations](../images/vector%20add.PNG)

In [2]:
u = np.array([2,3,4,5])

In [3]:
2*u # Scalar Multiplication

array([ 4,  6,  8, 10])

In [7]:
v = np.array([1,2,5,6])
u + v # Vector addition

array([ 3,  5,  9, 11])

In [8]:
u * v # Vector Multiplication

array([ 2,  6, 20, 30])

In [9]:
u / v # vector Division

array([2.        , 1.5       , 0.8       , 0.83333333])

In [10]:
v - u # Vector Subtraction

array([-1, -1,  1,  1])

### Multiplication

#### Vector-Vector(Two Coloumn Vectors) multiplication

![ColumnVectorDot](../images/vector%20vector%20product.PNG)

In [12]:
print(u)
print(v)
print(u.shape)
print(v.shape)
v.shape[0]

[2 3 4 5]
[1 2 5 6]
(4,)
(4,)


4

In [13]:
# Creating Function to dot product
def column_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0] #it will make sure if both vector has enough and equal element to do the product.
    n = u.shape[0] # Taking upper limit
    result = 0.0 # Empty array

    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [14]:
column_vector_multiplication(u,v) # Dot product using custom function

58.0

In [15]:
u.dot(v) # Dot product using built-in function

58

#### Vector-Vector(Row Coloumn Vectors) multiplication

![ColumnVectorDot](../images/vector%20vector%20dot%20product.PNG)

Calculation and codes are same as above.

#### Matrix-Vector multiplication

![ColumnVectorDot](../images/matrix-vector.PNG)
![ColumnVectorDot](../images/matrix-vector%20product%20rule.PNG)

In [16]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [17]:
U.shape

(3, 4)

In [18]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0] # Matrices column should be equal to vectors row
    
    num_rows = U.shape[0] # Taking upper limit
    
    result = np.zeros(num_rows) # Empty vector
    
    for i in range(num_rows):
        result[i] = column_vector_multiplication(U[i], v) # Using vector-vector multiplication as each row of matrix is like a vector.
    
    return result

In [19]:
matrix_vector_multiplication(U, v) # Dot product using custom function

array([71., 22., 21.])

In [20]:
U.dot(v)# Dot product using built-in function

array([71, 22, 21])

#### Matrix-Matrix multiplication

![ColumnVectorDot](../images/matrix-matrix%20multiplication.PNG)

In [21]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [22]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0] # Result vectors row
    num_cols = V.shape[1] # Result vectors col
    
    result = np.zeros((num_rows, num_cols)) # Empty matrix
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [23]:
matrix_matrix_multiplication(U, V) # Dot product using custom function

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [24]:
U.dot(V) # Dot product using built-in function

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix

In [25]:
I = np.eye(3)

In [27]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Inverse

In [33]:
Us = U[:,0:3]
Us

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2]])

In [35]:
U_Inv = np.linalg.inv(U) # It will return error as U is not a square matrix
U_Inv

LinAlgError: Last 2 dimensions of the array must be square

In [36]:
U_Inv = np.linalg.inv(Us) # It will run just fine as Us is a square matrix 
U_Inv

array([[-0.2       ,  0.2       ,  0.4       ],
       [-0.06666667,  0.73333333, -0.2       ],
       [ 0.33333333, -0.66666667, -0.        ]])